"""create carts cart_items orders order_items
Revision ID: 20260731_0003
Revises: 20260731_0002
"""
from alembic import op
import sqlalchemy as sa
revision='20260731_0003'; down_revision='20260731_0002'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('carts',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint('user_id'))
    op.create_index('ix_carts_user_id','carts',['user_id'])
    op.create_table('cart_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('cart_id',sa.Integer(),sa.ForeignKey('carts.id',ondelete='CASCADE'),nullable=False),sa.Column('product_id',sa.Integer(),sa.ForeignKey('products.id',ondelete='RESTRICT'),nullable=False),sa.Column('quantity',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.CheckConstraint('quantity > 0',name='ck_cart_items_quantity_positive'),sa.UniqueConstraint('cart_id','product_id',name='uq_cart_items_cart_product'))
    op.create_index('ix_cart_items_cart_id','cart_items',['cart_id']); op.create_index('ix_cart_items_product_id','cart_items',['product_id'])
    op.create_table('orders',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('order_code',sa.String(32),nullable=False),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('receiver_name',sa.String(120),nullable=False),sa.Column('receiver_phone',sa.String(30),nullable=False),sa.Column('delivery_address',sa.String(500),nullable=False),sa.Column('note',sa.Text()),sa.Column('subtotal',sa.Numeric(14,2),nullable=False),sa.Column('delivery_fee',sa.Numeric(14,2),nullable=False),sa.Column('discount_amount',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('total_amount',sa.Numeric(14,2),nullable=False),sa.Column('payment_method',sa.String(20),nullable=False,server_default='COD'),sa.Column('payment_status',sa.String(20),nullable=False,server_default='UNPAID'),sa.Column('order_status',sa.String(20),nullable=False,server_default='PENDING'),sa.Column('cancel_reason',sa.String(500)),sa.Column('cancelled_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.CheckConstraint("payment_method IN ('COD','STRIPE','PAYPAL','VNPAY')",name='ck_orders_payment_method'),sa.CheckConstraint("payment_status IN ('UNPAID','PENDING','PAID','FAILED','REFUNDED')",name='ck_orders_payment_status'),sa.CheckConstraint("order_status IN ('PENDING','CONFIRMED','PREPARING','DELIVERING','COMPLETED','CANCELLED')",name='ck_orders_order_status'),sa.UniqueConstraint('order_code'))
    op.create_index('ix_orders_order_code','orders',['order_code']); op.create_index('ix_orders_user_id','orders',['user_id']); op.create_index('ix_orders_order_status','orders',['order_status']); op.create_index('ix_orders_created_at','orders',['created_at'])
    op.create_table('order_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('order_id',sa.Integer(),sa.ForeignKey('orders.id',ondelete='CASCADE'),nullable=False),sa.Column('product_id',sa.Integer(),sa.ForeignKey('products.id',ondelete='SET NULL')),sa.Column('product_name',sa.String(120),nullable=False),sa.Column('product_image_url',sa.String(500),nullable=False),sa.Column('unit_price',sa.Numeric(14,2),nullable=False),sa.Column('quantity',sa.Integer(),nullable=False),sa.Column('line_total',sa.Numeric(14,2),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.CheckConstraint('quantity > 0',name='ck_order_items_quantity_positive'))
    op.create_index('ix_order_items_order_id','order_items',['order_id'])
def downgrade():
    op.drop_table('order_items'); op.drop_table('orders'); op.drop_table('cart_items'); op.drop_table('carts')
